### ISSUE TITLE
Slack Bot not responding to commands

### ISSUE THREAD

**Issue by toxic049** [fraschetti/Octoslack#112]
Hey Guys, 

ive been using Octoslack succesfully for little bit over a year now. since the latest updates i cant get the bot / slack app to respond to commands anymore. 

ive followed all the setings, and tested with the bot token and oauth permissions. what can i do to trouble shoot this? 

using: Octoprint Version 1.5.3, Octoslack 2.1.0

the bot is installed nicely and posts updates to my # General channel.

Thanks in advance.

**Comment by toxic049** [comment]
enabled debug logging:
1-01-24 11:22:06,719 - octoprint.plugins.Octoslack - ERROR - Error retrieving username for Slack message - User ID: UFKC3RF1D, Error: missing_scope
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_Octoslack/__init__.py", line 2598, in get_slack_username
    user_info_rsp = slackAPIConnection.users.info(userid)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/slacker/__init__.py", line 197, in info
    return self.get('users.info', params={'user': user, 'include_locale': include_locale})
  File "/home/pi/oprint/local/lib/python2.7/site-packages/slacker/__init__.py", line 117, in get
    api, **kwargs
  File "/home/pi/oprint/local/lib/python2.7/site-packages/slacker/__init__.py", line 99, in _request
    raise Error(response.error)
Error: missing_scope

**Comment by toxic049** [comment]
removed the users:read scope. and added it again to the bot oauth scopes. then reinstalled the app in slack now it works again.
