### ISSUE TITLE
Imgur integration failing

### ISSUE THREAD

**Issue by WyattNielsen** [fraschetti/Octoslack#99]
Integration was working previously but now I get the following error on each upload:

> ImgurClientError: (417) Internal expectation failed

I revoked access and re-authenticated with imgur and still see the same error. I've also tried a new album and removing the album to post anonymously. relevant log entries below.

> 2020-08-28 17:27:27,257 - octoprint.plugins.Octoslack - ERROR - Failed to upload snapshot to Imgur (ImgurClientError): Internal expectation failed, StatusCode: 417
> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_Octoslack/__init__.py", line 4837, in upload_asset
>     local_file_path, config=imgur_upload_config, anon=False
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/imgurpython/client.py", line 596, in upload_from_path
>     return self.make_request('POST', 'upload', data, anon)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/imgurpython/client.py", line 161, in make_request
>     raise ImgurClientError(response_data['data']['error'], response.status_code)
> ImgurClientError: (417) Internal expectation failed
> 2020-08-28 17:27:27,258 - octoprint.plugins.Octoslack - ERROR - ImgurClient Credits: {'UserRemaining': '1803', 'UserLimit': '2000', 'ClientRemaining': '12496', 'ClientLimit': '12500', 'UserReset': '3600'}
> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_Octoslack/__init__.py", line 4837, in upload_asset
>     local_file_path, config=imgur_upload_config, anon=False
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/imgurpython/client.py", line 596, in upload_from_path
>     return self.make_request('POST', 'upload', data, anon)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/imgurpython/client.py", line 161, in make_request
>     raise ImgurClientError(response_data['data']['error'], response.status_code)
> ImgurClientError: (417) Internal expectation failed

**Comment by WyattNielsen** [comment]
I updated my webcam configuration and got it to work, I'm guessing Octoslack was not able to capture the images and so it was sending an empty POST resulting in the above error. Would be nice to have a validation and error if the image isn't captured.
